definitions:
  controllers.CreateUserRequest:
    properties:
      email:
        type: string
      name:
        minLength: 3
        type: string
      password:
        minLength: 6
        type: string
    required:
    - email
    - name
    - password
    type: object
info:
  contact: {}
paths:
  /user:
    post:
      consumes:
      - application/json
      description: Add new fake User Account
      parameters:
      - description: User
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/controllers.CreateUserRequest'
      produces:
      - application/json
      responses: {}
      summary: Post User Data
      tags:
      - User
  /user/{id}:
    get:
      consumes:
      - application/json
      description: Get Dummy User Account
      parameters:
      - description: ID
        in: path
        name: id
        type: integer
      produces:
      - application/json
      responses: {}
      summary: Get User Data
      tags:
      - User
swagger: "2.0"
